const productData = [
  {
    id: 1,
    poNo: "PO101",
    destination: "Chaina",
    inspectionDate: new Date().toLocaleDateString(),
    shipmentMode: "Air",
    shipmentDate: new Date().toLocaleDateString(),
    orderQty: 5000,
    orderUOM: "pc",
    excess: 2,
    wastage: 2,

    details: [
      {
        id: 101,
        color: "Red",
        orderQty: 2000,
        extra: 0,
        withExtra: 2000,
        previous: 800,
        layCount: 0,
        cutQuantity: 0,
        balance: 1200,
      },
      {
        id: 102,
        color: "Red",
        orderQty: 2000,
        extra: 0,
        withExtra: 2000,
        previous: 0,
        layCount: 0,
        cutQuantity: 0,
        balance: 2000,
      },
    ],
  },
  {
    id: 2,
    poNo: "PO102",
    destination: "Chaina",
    inspectionDate: new Date().toLocaleDateString(),
    shipmentMode: "Air",
    shipmentDate: new Date().toLocaleDateString(),
    orderQty: 7000,
    orderUOM: "pc",
    excess: 2,
    wastage: 2,
    details: [
      {
        id: 103,
        color: "Green",
        orderQty: 2000,
        extra: 0,
        withExtra: 2000,
        previous: 0,
        layCount: 0,
        cutQuantity: 0,
        balance: 2000,
      },
      {
        id: 104,
        color: "Yellow",
        orderQty: 2000,
        extra: 0,
        withExtra: 2000,
        previous: 0,
        layCount: 0,
        cutQuantity: 0,
        balance: 2000,
      },
      {
        id: 105,
        color: "Green",
        orderQty: 2000,
        extra: 0,
        withExtra: 2000,
        previous: 0,
        layCount: 0,
        cutQuantity: 0,
        balance: 2000,
      },
    ],
  },
];
export default productData;
